
export const CLOSE_ADD_STOCK = "CLOSE_ADD_STOCK"
export const CLOSE_REMOVE_STOCK = "CLOSE_REMOVE_STOCK"

export const OPEN_ADD_STOCK = "OPEN_ADD_STOCK"
export const OPEN_REMOVE_STOCK = "OPEN_REMOVE_STOCK"

